src/Entity/Producto.php
<?php

namespace App\Entity;

use App\Repository\ProductoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductoRepository::class)]
class Producto
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToMany(targetEntity: Valoracion::class, mappedBy: 'id_producto')]
    private Collection $valoracions;

    #[ORM\Column(length: 255)]
    private ?string $nombre = null;

    #[ORM\ManyToOne(inversedBy: 'productos')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Artista $artista = null;

    #[ORM\Column(length: 255)]
    private ?string $ano_salida = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $precio = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pais = null;

    #[ORM\ManyToOne]
    private ?Formato $formato = null;

    #[ORM\OneToMany(targetEntity: LineaPedido::class, mappedBy: 'producto')]
    private Collection $lineaPedidos;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imagen = null;

    public function __construct()
    {
        $this->valoracions = new ArrayCollection();
        $this->lineaPedidos = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->nombre;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Valoracion>
     */
    public function getValoracions(): Collection
    {
        return $this->valoracions;
    }

    public function addValoracion(Valoracion $valoracion): static
    {
        if (!$this->valoracions->contains($valoracion)) {
            $this->valoracions->add($valoracion);
            $valoracion->setIdProducto($this);
        }

        return $this;
    }

    public function removeValoracion(Valoracion $valoracion): static
    {
        if ($this->valoracions->removeElement($valoracion)) {
            // set the owning side to null (unless already changed)
            if ($valoracion->getIdProducto() === $this) {
                $valoracion->setIdProducto(null);
            }
        }

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getArtista(): ?Artista
    {
        return $this->artista;
    }

    public function setArtista(?Artista $artista): static
    {
        $this->artista = $artista;

        return $this;
    }

    public function getAnoSalida(): ?string
    {
        return $this->ano_salida;
    }

    public function setAnoSalida(string $ano_salida): static
    {
        $this->ano_salida = $ano_salida;

        return $this;
    }

    public function getPrecio(): ?string
    {
        return $this->precio;
    }

    public function setPrecio(string $precio): static
    {
        $this->precio = $precio;

        return $this;
    }

    public function getPais(): ?string
    {
        return $this->pais;
    }

    public function setPais(?string $pais): static
    {
        $this->pais = $pais;

        return $this;
    }

    public function getFormato(): ?Formato
    {
        return $this->formato;
    }

    public function setFormato(?Formato $formato): static
    {
        $this->formato = $formato;

        return $this;
    }

    /**
     * @return Collection<int, LineaPedido>
     */
    public function getLineaPedidos(): Collection
    {
        return $this->lineaPedidos;
    }

    public function addLineaPedido(LineaPedido $lineaPedido): static
    {
        if (!$this->lineaPedidos->contains($lineaPedido)) {
            $this->lineaPedidos->add($lineaPedido);
            $lineaPedido->setProducto($this);
        }

        return $this;
    }

    public function removeLineaPedido(LineaPedido $lineaPedido): static
    {
        if ($this->lineaPedidos->removeElement($lineaPedido)) {
            // set the owning side to null (unless already changed)
            if ($lineaPedido->getProducto() === $this) {
                $lineaPedido->setProducto(null);
            }
        }

        return $this;
    }

    public function getImagen(): ?string
    {
        return $this->imagen;
    }

    public function setImagen(?string $imagen): static
    {
        $this->imagen = $imagen;

        return $this;
    }
}

src/Controller/ProductoController.php
<?php

namespace App\Controller;

use App\Entity\Artista;
use App\Entity\Formato;
use App\Entity\Producto;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted("ROLE_USER")]
class ProductoController extends AbstractController
{
    #[Route('/producto/{id}', name: 'app_productos')]
    public function showProductoById(EntityManagerInterface $entityManager, int $id): Response
    {

        $productoRepository = $entityManager->getRepository(Producto::class);
        $producto = $productoRepository->find($id);

        $todosProductos = $productoRepository->findAll();

        shuffle($todosProductos);

        $productosRecomendados = array_slice($todosProductos, 0, 4);

        $formatos = $entityManager->getRepository(Formato::class)->findAll();

        $artistaRepository = $entityManager->getRepository(Artista::class);

        $artista = $artistaRepository->findOneById($producto->getArtista()->getId());

        $artistaFinal = $entityManager->getRepository(Artista::class)->find($artista[0]['id']);

//        if (!$producto) {
//            throw $this->createNotFoundException("No se encuentra ningún producto. Siga buscando");
//        }
        return $this->render('producto/index.html.twig', [
            'producto' => $producto,
            'artista' => $artistaFinal,
            'formatos' => $formatos,
            'productos_recomendados' => $productosRecomendados,
        ]);
    }

    public function showAllProducts(EntityManagerInterface $entityManager) {
        $productos = $entityManager->getRepository(Producto::class)->findAll();


    }
}

templates/producto/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ producto.nombre }} - {{ producto.artista }}{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{{ asset('styles/producto.css') }}">
{% endblock %}


{% block body %}
    {% include('components/navbar.html.twig') %}

    <section class="py-5 text-light">
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-items-center">
                <div class="col-md-6">
                    <img class="card-img-top mb-5 mb-md-0" src="{{ asset('musica/'~producto.artista~' - '~producto.nombre~' ['~producto.anoSalida~']/cover.jpg') }}" alt="..." />
                    <audio class="text-center" src="{{ asset('musica/'~producto.artista~' - '~producto.nombre~' ['~producto.anoSalida~']/test.mp3') }}" controls>sfkdslfjksd</audio>
                </div>
                <div class="col-md-6">
                    <h1 class="display-5 fw-bolder">{{ producto.nombre }} ({{ producto.anoSalida }})</h1>
                    <h3><a href="{{ path('prod_por_artista', {id:artista.id}) }}">{{ producto.artista }}</a></h3>
                    <div class="fs-5 mb-5">
                        <span>{{ producto.precio }}€</span>
                    </div>
                    {% if artista.descripcion is not null %}
                        <p>{{ artista.descripcion }}</p>
                    {% endif %}
                    <p>Formato: {{ producto.formato }}</p></a>
                    <div class="d-flex">
                        <form action={{ path('add_carrito', {id: producto.id}) }}>
                            <input class="btn btn-dark flex-shrink-0" type="submit" value="Añadir al carrito">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Related items section-->
    <section class="py-5 bg-light">
        <div class="container px-4 px-lg-5 mt-5">
            <h2 class="fw-bolder mb-4">Otros productos</h2>
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for producto in productos_recomendados %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                           <a  href="{{ path('app_productos', {id: producto.id }) }}"><img class="card-img-top" href="{{ path('app_productos', {id: producto.id }) }}" src="{{ asset('musica/'~producto.artista~' - '~producto.nombre~' ['~producto.anoSalida~']/cover.jpg') }}" alt="..." /></a>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ producto.nombre }}</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>
                                    <!-- Product price-->
                                    {{ producto.precio }}€
                                </div>
                            </div>
                            <!-- Product actions-->
{#                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">#}
{#                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>#}
{#                            </div>#}
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section>
{% endblock %}
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
{% endblock %}